### ISSUE TITLE
Remove the default value for triageLabel

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab-probot#12]
### Problem

As noted in https://github.com/jupyterlab/jupyterlab-probot/pull/11#issuecomment-1018725789 , the triage label introduced in #11 is applying to repositories such as `jupyter_releaser` that do not have a triage process. This introduces noise to new issues on those repos.

### Proposed Solution

Remove the default value for triageLabel, allowing repos to set it explicitly (e.g., in https://github.com/jupyterlab/jupyterlab/issues/11911 ).

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab-probot/pull/13, thanks!
